version: '2.2'

services:
  app:
    build: .
    container_name: library_app
    volumes:
    - ./app/:/opt/django/app/
    depends_on:
      - database
  database:
    image: postgres:14.0-alpine
    container_name: library_db
    ports:
     - "6000:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
