services:
  database:
    ports:
      - "6000:5432"
    env_file:
      - ./.env.db
  app:
    command: python manage.py runserver 0.0.0.0:9000
    ports:
      - "9000:9000"
    env_file:
      - ./.env
volumes:
  postgres_data:
