services:
  database:
    image: postgres:14.0-alpine
    container_name: library_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  app:
    build: .
    container_name: library_app
    volumes:
    - ./app/:/app
    depends_on:
      - database
volumes:
  postgres_data:
