services:
  database:
    ports:
      - "7000:5432"
    env_file:
      - ./.env.db
  app:
    command: gunicorn library.wsgi:application --bind 0.0.0.0:9000
    ports:
      - "3000:9000"
    env_file:
      - ./.env.prod
volumes:
  postgres_data:
