version: '2.2'

services:
  app_prod:
    command:  gunicorn desafio_magalu.wsgi:application --bind 0.0.0.0:9000
    extends:
     service: app
     file: docker-compose.yml
    ports:
      - "9000:9000"
    env_file:
      - ./.env.prod
  database_prod:
    extends:
      service: database
      file: docker-compose.yml
    ports:
     - "6000:5432"
    env_file:
      - ./.env.prod.db
volumes:
  postgres_data:
